apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-prod

resources:
  - ../../base

# Kustomize image transform — updated by cd-promote.yml via PR
images:
  - name: ghcr.io/datafreakk/todo-api
    newTag: latest  # replaced by cd-promote.yml PR

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: todo-api

replicas:
  - name: todo-api
    count: 3
