apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-api-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/Datafreakk/todo-gitops.git
    targetRevision: main       # only changes via PR — cd-promote.yml opens the PR
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10    # keep more history for prod rollbacks
