apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev

resources:
  - ../../base

# Kustomize image transform — CI updates this value via:
# kustomize edit set image ghcr.io/datafreakk/todo-api=ghcr.io/datafreakk/todo-api:sha-<commit>
images:
  - name: ghcr.io/datafreakk/todo-api
    newTag: latest  # replaced by ci.yml on every push to main

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: todo-api

replicas:
  - name: todo-api
    count: 1
